name: debugging_xdebug_lando

recipe: drupal8

env_file:
  - .env

config:
  webroot: web
  php: '8.0'
  via: nginx:1.18

proxy:
  appserver_nginx:
    - debugging-xdebug-lando.com

services:
  appserver:
    composer_version: '1.10.17'
    xdebug: true
  database:
    type: mariadb:10.2
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    scanner: false
